### ISSUE TITLE
Dimension specific render distance

### ISSUE THREAD

**Issue by noxifoxi** [henkelmax/dynamic-render-distance#1]
I'd like to suggest dimension specific render distance, like this - _no longer maintained_ - mod had done and worked fine until it lasted: https://github.com/BasiqueEvangelist/worldspecificviewdistance-fabric

This would be especially useful in the nether, because of the fog and the obstructive nature, you effectively can only see 8 chunks far. Not sharing the same render distance on all dimensions further improves server performance.

PS:
A few months ago I opened an [issue there suggesting dynamic render distance](https://github.com/BasiqueEvangelist/worldspecificviewdistance-fabric/issues/2) to their mod, but unfortunately they then decided to abandon the project.

**Comment by henkelmax** [comment]
This would increase the complexity of this mod unnecessarily. This is a very simple mod that just changes the values according to the performance
