### ISSUE TITLE
View Distance Tweaks added features

### ISSUE THREAD

**Issue by SulpherStaer** [henkelmax/dynamic-render-distance#2]
https://papermc.io/forums/t/1-14-1-17-view-distance-tweaks/3432

This mod has some excellent settings that it adds, and instead of making a feature request for each of them individually I thought I'd make one ticket with the things I'd like to see.

- **Start up delay** | For when the server has just booted and is still settling after a restart
- **Passed checks before adjustment** | So that it view distance does not jojo between two values each check. The config file of VDT explains why this is a good setting.
- **Chunk Count** | When a server is aware of how many chunks it can effectively load without latency it would be nice that the view distance is adjusted to maintain this value.
- **TPS/MSPT Prediction** | So that the setting isn't adjusted back and forth between two values where the higher one causes the additional lag to lower it again.

Anyway, a lot of the settings in VDT seem useful to keep a server healthy beyond just checking MSPT every 10 seconds. 

I appreciate you creating this mod, as I've been looking for a mod that gives this functionality (Variable view distance) for quite a while. Ticktools exists, but it causes chunk loading issues.

**Comment by henkelmax** [comment]
1. The mod only adjusts the distance when a player is online
2. This already exists implicitly
3. How would that work?
4. Same as 2.
