### ISSUE TITLE
(1.18) Make render distance and simulation distance independent //split up

### ISSUE THREAD

**Issue by Nickishero** [henkelmax/dynamic-render-distance#4]
**Is your feature request related to a problem? Please describe.**
Currently, only min and max render distance can be set. This includes min and max simulation distance.

**Describe the solution you'd like**
What I'd love to see, is being able to set these 2 independently from one another.

**Describe alternatives you've considered**
-

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/37247484/144329061-3b3f8a8c-0505-400f-9198-e3da6c9e9951.png)
As you can see, render distance === simulation distance.

**Comment by henkelmax** [comment]
#3
