### ISSUE TITLE
Add config option for server console messages to be debug instead of info (Request)

### ISSUE THREAD

**Issue by ghost** [henkelmax/dynamic-render-distance#6]
**Is your feature request related to a problem? Please describe.**
The problem I am having is that there are so many messages from dynamic render distance in my server console that it is annoying, I like to read the console to see what players are doing and see warn messages.

**Describe the solution you'd like**
I would like an option in the config to change the messages from dynamic render distance from info messages to debug messages so that they no longer appear in the server console.

**Describe alternatives you've considered**
I've tried changing the mspt boundaries so that changes trigger less often but its not a complete solution and it forces me to use a wider mspt range than I would like

**Additional context**
I am using fabric 1.18

**Comment by ghost** [comment]
@henkelmax <3

**Comment by ghost** [comment]
please!
![image](https://user-images.githubusercontent.com/82549089/146095020-94cda00a-d2c1-4cd4-8268-a3e8a44f2c08.png)
@henkelmax @GotoFinal

**Comment by henkelmax** [comment]
Please stop spamming. I have other stuff to do than maintaining mods every day!

**Comment by solonovamax** [comment]
@henkelmax I could provide a PR for these changes if you'd accept it.
Would that work?

**Comment by henkelmax** [comment]
I'm currently reevaluating the general concept of the mod, since changing the render distance is not a good option for 1.18 anymore. So this project is on halt until I've found an elegant solution for that.

**Comment by solonovamax** [comment]
What do you mean by "not a good option"?
Is it an issue with mojang's code, or something else?
I might be able to help with alternative solutions

**Comment by henkelmax** [comment]
Changing the render distance currently reloads all chunks on the client, like when pressing F3+A

**Comment by GotoFinal** [comment]
> Changing the render distance currently reloads all chunks on the client, like when pressing F3+A

Can be fixed on client side, the sodium fixes it for example. Not perfect ofc... the only other way is to just change it less often. Unless you just lie to client to always be on max distance and send less, but no idea how client will react to that.

**Comment by henkelmax** [comment]
I'm planning on making it only change the simulation distance, but haven't got the time to do it yet.

**Comment by GotoFinal** [comment]
> I'm planning on making it only change the simulation distance, but haven't got the time to do it yet.

then the mod name would need change to, and simulation distance have much smaller difference on load and in general its not needed to be high, and its clamped by view distance anyways.

**Comment by solonovamax** [comment]
> > Changing the render distance currently reloads all chunks on the client, like when pressing F3+A
> 
> Can be fixed on client side, the sodium fixes it for example. Not perfect ofc... the only other way is to just change it less often. Unless you just lie to client to always be on max distance and send less, but no idea how client will react to that.

Sodium does not fix this.
At least, not on version `0.4.0-alpha6+build.14`, which is the one I'm using atm in 1.18.1

**Comment by henkelmax** [comment]
> then the mod name would need change to, and simulation distance have much smaller difference on load and in general its not needed to be high, and its clamped by view distance anyways.

Yeah, that's why I'm debating about actually abandoning this project

**Comment by solonovamax** [comment]
> I'm planning on making it only change the simulation distance, but haven't got the time to do it yet.

Personally, I find the render distance changes useful.
Perhaps they could be kept, but could have one (or more) of the following done?
- Disabled by default
- A separate (longer) timer from the simulation distance
- A separate mspt threshold

**Comment by ghost** [comment]
> I'm debating about actually abandoning this project

In that case I will close the ticket, I believe there is an alternative mod that does similar things called Dynamic View if anyone is interested
